# Generated by Django 3.1.7 on 2021-03-06 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210306_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 6, 19, 3, 19, 345850)),
        ),
    ]
