# Generated by Django 3.1.7 on 2021-03-08 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210308_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 21, 9, 39, 647917)),
        ),
    ]
