# Generated by Django 3.1.7 on 2021-03-14 15:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210309_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='catalogue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), blank=True, null=True, size=None),
        ),
    ]
