# Generated by Django 3.1.7 on 2021-03-14 15:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_newuser_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='catalogue',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=10),
        ),
    ]
