# Generated by Django 3.1.7 on 2021-03-14 15:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210314_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='curr_reading',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='newuser',
            name='readed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
