# Generated by Django 3.1.7 on 2021-03-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210325_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
