# Generated by Django 3.1.7 on 2021-04-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210404_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='bid',
            field=models.CharField(max_length=20),
        ),
    ]
