# Generated by Django 3.1.7 on 2021-04-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_comments_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
    ]
