# Generated by Django 3.1.7 on 2021-04-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_comments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.TextField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
