# Generated by Django 3.1.7 on 2021-04-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_comments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='date',
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.TextField(max_length=30),
        ),
    ]
